name: aipfs-agent

services:
  aipfs-agent-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: aipfs-agent-backend
    container_name: aipfs-agent-backend
    ports:
      - "17890:1789"
    env_file:
      - ../.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - aipfs-agent

  ipfs-node:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    ports:
      - "4001:4001"  # IPFS swarm
      - "5001:5001"  # IPFS API
      - "8080:8080"  # IPFS Gateway
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server  # Optimize for server deployment
      - IPFS_PATH=/data/ipfs
      - IPFS_LOGGING=INFO
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - aipfs-agent

networks:
  aipfs-agent:
    name: aipfs-agent
    driver: bridge

volumes:
  ipfs_data: